apiVersion: v1
kind: Secret
metadata:
  name: healthnova-secrets
  namespace: healthnova
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:Khan0085@localhost:5432/healthnova_db"
  JWT_ACCESS_SECRET: "your_super_secret_access_key_change_this"
  JWT_REFRESH_SECRET: "your_super_secret_refresh_key_change_this"
  GROQ_API_KEY: "your_groq_api_key_here"
  GEMINI_API_KEY: "your_gemini_api_key_here"
  RESEND_API_KEY: "re_your_actual_key_here"
  STRIPE_SECRET_KEY: "sk_test_your_key_here"
