import { Router, Request, Response } from "express";

const router = Router();

// Middleware to verify secret header from n8n
const verifyN8nSecret = (req: Request, res: Response, next: any) => {
  const secret = req.headers["x-n8n-secret"];
  if (secret !== process.env.N8N_SECRET_TOKEN) {
    return res.status(403).json({ error: "Unauthorized n8n trigger" });
  }
  next();
};

router.post(
  "/update-report-summary",
  verifyN8nSecret,
  async (req: Request, res: Response) => {
    const { patientId, reportSummary, urgency } = req.body;

    // Update DB with AI Summary generated by n8n
    // await MedicalRecord.findByIdAndUpdate(...)

    res.json({ success: true, message: "Record updated via n8n" });
  },
);

export default router;
